### ISSUE TITLE
Support multiple hosts/machines

### ISSUE THREAD

**Issue by eyadsibai** [Misterio77/nix-starter-configs#1]
Great templates. Thanks a lot! Would be great if it can support multiple hosts/devices.

**Comment by Misterio77** [comment]
Thanks for your kind words! Here's a snippet on how to multihost (based on the standard template):

```nix
{
  # ...
  nixosConfigurations = {
      foo = nixpkgs.lib.nixosSystem {
      pkgs = legacyPackages.x86_64-linux;
      modules = [
        ./nixos/foo/configuration.nix
      ] ++ (builtins.attrValues nixosModules);
      specialArgs = { inherit inputs; };
    };
    bar = nixpkgs.lib.nixosSystem {
      pkgs = legacyPackages.aarch64-linux;
      modules = [
        ./nixos/bar/configuration.nix
      ] ++ (builtins.attrValues nixosModules);
      specialArgs = { inherit inputs; };
    };
  };
  # ...
}
```

If you have a lot of hosts, you can of course make a function for it:
```nix
{
  # ...
  nixosConfigurations =
    let mkHost = system: hostname: nixpkgs.lib.nixosSystem {
      pkgs = legacyPackages.${system};
      modules = [
        ./nixos/${hostname}/configuration.nix
      ] ++ (builtins.attrValues nixosModules);
      specialArgs = { inherit inputs; };
    };
    in {
      foo = mkHost "x86_64-linux" "foo";
      bar = mkHost "aarch64-linux" "bar";
    };
  # ...
}
```

I might make a template with a few similar functions and examples. Thanks for the feedback!

**Comment by MTRNord** [comment]
Hi :)

I am new to nixos and got this basically working thanks to the template! I am wanting to use this for 4 nodes which are mostly the same with minor differences. Therefor, I am wondering what would be the best way to have "common" settings with this template, which then can be overridden or extended on a per-node basis. :) Did anyone already do this or has an example?

**Comment by Misterio77** [comment]
Hey @MTRNord, sorry for the late reply!

I do some of that on [my own config](https://github.com/misterio77/nix-config). I like to make a directory for each host, as well as a common one. Then you can just add the common modules to `imports = [ ... ]` and it works nicely!

The original issue has been addressed (it's supported!), so I'll close this for now. If anyone has a related question, do feel free to comment here anyway :)
