### ISSUE TITLE
error: executing 'git': No such file or directory

### ISSUE THREAD

**Issue by LudovicoSforza** [Misterio77/nix-starter-configs#10]
![image](https://user-images.githubusercontent.com/44255157/202428763-e29016f9-9f7a-4a91-8c0a-aab984142835.png)
I got this error when I run ```sudo nixos-rebuild switch --flake .#```. How do I fix it?
I'm using the Standard version.

**Comment by LudovicoSforza** [comment]
Fixed with this command `sudo nix shell nixpkgs#git -c nixos-rebuild switch --flake .` :+1:

**Comment by Misterio77** [comment]
The easiest way would be to use the provided `shell.nix` through `nix-shell` (`nix develop` also works, but the experimental features flag and git available to work); it automatically provides you with the latest nix, git and enables the experimental features.
