### ISSUE TITLE
Repo needs a license

### ISSUE THREAD

**Issue by TassiloBalbo** [Misterio77/nix-starter-configs#11]
Hello, licenses are boring I know. But if you don't include a free and open-source license, it means that the author has exclusive copyright rights. This would mean that no one can do anything with this repo.

You could for example use [The Unlicense](https://choosealicense.com/licenses/unlicense/) license, which is straight forward and gives everybody the right to use and modify code in this repo.

So please consider adding a free and open-source license. Thank you!

**Comment by Misterio77** [comment]
Thanks! Totally an oversight on my part. Fixed on https://github.com/Misterio77/nix-starter-configs/commit/ba725c1d6cbb361a428f86e989b7d14f2a456ed1.
