### ISSUE TITLE
Home manager does not install or build with config (reproducer included)

### ISSUE THREAD

**Issue by ParetoOptimalDev** [Misterio77/nix-starter-configs#13]
My understanding is that this config is using home-manager as a nixos module. So whenever you do `nixos-rebuild switch` or `nixos-rebuild vm` the home-manage configuration should ge run too.

That doesn't happen though, and you can reproduce locally with:

```sh
git clone https://github.com/ParetoOptimalDev/try-nix-starter-config
cd try-nix-starter-config
git checkout a7d38df74b1d46631e7026f9a76ff23e5fbd7588
nixos-rebuild build-vm --flake .#your-hostname
/result/bin/run-your-hostname-vm 
# you can login with username and password nixos
```

related to #12. After reading #12 I thought "Oh... maybe the home-manager binary is available even though the home-manager nixos module wasn't run".

However `home-manager` in the shell after logging in returns `home-manager: command not found`.

**Comment by DavSanchez** [comment]
Hi, here `home-manager` acts here as a stand-alone installation. If it was a NixOS module then the reference to a `home.nix` file would be inside the `nixosConfigurations` attrset's `modules`:

```nix
    nixosConfigurations = {
      hostname = nixpkgs.lib.nixosSystem {
        system = "x86_64-linux";
        modules = [
          ./configuration.nix
          home-manager.nixosModules.home-manager
          {
            home-manager.useGlobalPkgs = true;
            home-manager.useUserPackages = true;
            home-manager.users.jdoe = import ./home.nix;
            # Optionally, use home-manager.extraSpecialArgs to pass
            # arguments to home.nix
          }
        ];
      };
    };
```

What is discussed in #12 is that apparently a `home-manager` needs to be activated when used **for the first time**.

According to the [`home-manager` manual section for stand-alone installs using flakes](https://nix-community.github.io/home-manager/index.html#sec-flakes-standalone), you should do this first:

```console
$ nix build --no-link <flake-uri>#homeConfigurations.jdoe.activationPackage
$ "$(nix path-info <flake-uri>#homeConfigurations.jdoe.activationPackage)"/activate
```

Then `home-manager` will be correctly sourced on the login shell and subsequent calls to `home-manager switch --flake '<flake-uri>#jdoe'` should work.

The manual seems says that from `21.05` onwards you can do just `home-manager switch --flake '<flake-uri>#jdoe'` and it will be expanded to the correct `activationPackage`, but it did not work in my case in `22.05`. I needed to `activate` it first using the above 2 commands before `home-manager switch --flake '<flake-uri>#jdoe'` started to work properly.

**Comment by Misterio77** [comment]
@DavSanchez is correct, this template provides a standalone home-manager config. As they showed, it's pretty simple to use it as a NixOS module instead, if you prefer.

I would add, however, that getting the `home-manager` is easier than remembering that big `nix build` command: `nix shell nixpkgs#home-manager` should get you going. You can alternatively use the [provided shell.nix](https://github.com/Misterio77/nix-starter-configs/blob/main/standard/shell.nix) that automatically provides you with the latest `nix` (with flakes and nix-command enabled), `git`, and `home-manager`

**Comment by ParetoOptimalDev** [comment]
Thank you both for your help. Your answers make sense but leave me with some questions.

Doesn't using home-manager as a nixos module subsume the standalone home-manager case?

Plus it would seem to avoid the user not having home-manager like I did.

Are there downsides to using the home-manager module?
