### ISSUE TITLE
home-manager both standalone and NixOS module at the same time?

### ISSUE THREAD

**Issue by wheelie-turner** [Misterio77/nix-starter-configs#14]
Hi,

first of all, thanks a lot. Editing smth in nix and writing from scratch are two very different things for someone who is not really familiar with nix programming language and its libs[docs suck as well :( ]. Having such template helps so much.

Let me first give the context for my question.
- `home/test.nix` contains my home-manager config for user `test`
- there is `homeConfiguration` which includes `home/test.nix` as a module
- there is `nixosConfiguraion` which includes `home-manager.nixosModules.home-manager { home-manager.useGlobalPkgs = true; home-manager.useUserPackages = true; home-manager.users.test = import ./home/test.nix;}` as a module.

Now, deploying both `nixosConfiguration` with `nixos-rebuild` and `homeConfiguration` with `home-manager` should produce same environment for the user, since it's the same `home/test.nix`.

What I want:
- to be able to easily change configuration using `home-manager` command without rebuilding whole system(add new packages, configure them, commit `home/test.nix`)
- at the same time, every time my system is being updated using `nixos-rebuild`, I want user environment to be updated as well

Right now if I deploy using `nixos-rebuild` , there's no `home-manager` command available for the user, despite having `programs.home-manager.enable = true;` in `home/test.nix`, which puzzles me quite a bit.

I did read in #12 that I can create a generation of home-manager and activate it manually, but as I understand next nixos configuration being built will create new generation of home-manager configuration without `home-manager` command available again. Also would be nice to avoid doing it manually. This is what `programs.home-manager.enable = true;` should be for, in my understanding.

Could you please advice how can I achieve what I want?

**Comment by Misterio77** [comment]
Hey!

This setup you mentioned is not something I've seen implemented yet.

You basically can't use standalone home-manager and home-manager as a nixos module at the same time, as they're different implementations entirely. What might be possible is to also build the standalone home-manager setup and perhaps make the user run it on login. I'll see if I can get something soimilar going.

**Comment by wheelie-turner** [comment]
Hi,

thanks, you are right it's working, I was just confused by `programs.home-manager.enable = true;` not installing `home-manager` package to user environment, I guess.

One last thing: is it possible to add `pkgs.home-manager` to either `users.users.<name>.packages` or `environment.systemPackages` from the main `flake.nix`? Smth like:
```
home-manager.nixosModules.home-manager { 
  home-manager.useGlobalPkgs = true; 
  home-manager.useUserPackages = true; 
  home-manager.users.test = import ./home/test.nix;
  <smth>.users.test.packages = [nixpkgs.home-manager];    # ???
}
```

Point is to be able to fully enable/disable home-manager by commenting out the section in `flake.nix` instead of editing multiple files. It's a nitpick, really. Works great otherwise.

Thanks.

**Comment by Misterio77** [comment]
> One last thing: is it possible to add pkgs.home-manager to either users.users.<name>.packages or environment.systemPackages from the main flake.nix?

Sure is. Something like this should work:
```nix
{
  "misterio@atlas" = home-manager.lib.homeManagerConfiguration {
    pkgs = nixpkgs.legacyPackages."x86_64-linux";
    extraSpecialArgs = { inherit inputs outputs; };
    modules = [
      ./home/misterio/atlas.nix
      ({ pkgs, ...}: {
        home-manager = {
          useUserPackages = true;
          users.misterio = import ./home/misterio/atlas.nix;
        };
        users.users.misterio.packages = [ pkgs.home-manager ];
      })
    ];
  };
}
```

**Comment by wheelie-turner** [comment]
And thanks again!
Your example was for `homeManagerConfiguration`, but it **seems to work** for `nixosSystem` as well, even without `pkgs = nixpkgs.legacyPackages."x86_64-linux";`. At least `nixos-rebuild` doesn't complain about it.
```nix
  {
        test-system = nixpkgs.lib.nixosSystem {
          specialArgs = { inherit inputs outputs; };
          modules = [
            ./hosts/test-system
            home-manager.nixosModules.home-manager {
              home-manager.useGlobalPkgs = true;
              home-manager.useUserPackages = true;
              home-manager.users.test = import ./home/test/test-system.nix;
            }
            ({pkgs, ...}: {
              users.users.test.packages = [ pkgs.home-manager ];
            })
          ];
        };
  }
```

**Comment by Misterio77** [comment]
Oops, that was a typo.
