### ISSUE TITLE
Please dokument on how to add a custom package to configurattion.nix

### ISSUE THREAD

**Issue by ngiger** [Misterio77/nix-starter-configs#16]
I successfully created a package simpleScript which I can run via nix run .#simpleScript` 

But when I try to add it to my configuration.nix it fails:

<pre>
 sudo nixos-rebuild dry-build --flake .#your-hostname
building the system configuration...
warning: Git tree '/opt/src/nix-starter-config' is dirty
error: attribute 'simpleScript' missing

       at /nix/store/1lm85rfzigx86v60yy3fab9qjddlqq2y-source/standard/nixos/configuration.nix:61:43:

           60|   };
           61|   environment.systemPackages = [ pkgs.vim pkgs.simpleScript ];
             |                                           ^
           62|   # FIXME: Add the rest of your current configuration
(use '--show-trace' to show detailed location information)
</pre>

Patch for this example is attached.

[example.ZIP](https://github.com/Misterio77/nix-starter-configs/files/10303673/example.ZIP)

**Comment by Misterio77** [comment]
Heyy. Try uncommenting these lines https://github.com/Misterio77/nix-starter-configs/blob/main/standard/nixos/configuration.nix#L25

I chose to make the overlay applying a little more explicit, but perhaps this should be uncommented by default.

**Comment by Misterio77** [comment]
Closing this for now, to help track what's left to do. Feel free to reopen if you are still facing trouble!
