### ISSUE TITLE
[Standard] "error: attribute 'outputs' missing"

### ISSUE THREAD

**Issue by zyxophobia** [Misterio77/nix-starter-configs#22]
Hi there! I found this template while looking through GitHub, and since I'm genuinely urging to try out NixOS, I thought I'd give this one a go.

I slightly modified the standard config and gave it a run… and I got an error. The error is mentioned in the title — `error: attribute 'outputs' missing` was on the screen. Here's the full error seen when running `nix flake check`:

```
[zyx@apollyon:~/.zetup]$ nix flake check

warning: unknown flake output 'homeManagerModules'
error: attribute 'outputs' missing

       at /nix/store/4bdz2j6lry2vl44bcdaaarcap1p7qfpb-source/lib/modules.nix:483:28:

          482|         builtins.addErrorContext (context name)
          483|           (args.${name} or config._module.args.${name})
             |                            ^
          484|         ) (lib.functionArgs f);
```

Here is a SourceBin paste of my `flake.nix`: https://srcb.in/BubS6kb87l

I'm still learning NixOS, so this is something I am almost completely unfamiliar with. All help is appreciated!

**Comment by Misterio77** [comment]
Hello!

Hmm, that's weird. Your flake seems okay, `outputs` is being passed as expected.
Can you perhaps provide the entire config so I can try to reproduce it as well?

**Comment by zyxophobia** [comment]
Of course! This is still a massive work in progress, but here's the current state of the config, nice and fancy in a Git repository. I had modified the files slightly to fit my needs, and I'm unsure what silly mistake I could have made here!

https://github.com/zyxophobia/config.nix

**Comment by Misterio77** [comment]
Your config looks very nice so far :), I absolutely love the comments.

You're missing a `outputs` in hm's `extraSpecialArgs` (`nixos/users.nix`). Here's a patch that should get you going:

```diff
diff --git a/nixos/users.nix b/nixos/users.nix
index cc760a3..755ca8f 100644
--- a/nixos/users.nix
+++ b/nixos/users.nix
@@ -1,10 +1,10 @@
-{ inputs, ...}: {
+{ inputs, outputs, ...}: {
   imports = [
     inputs.home-manager.nixosModules.home-manager
   ];
 
   home-manager = {
-    extraSpecialArgs = { inherit inputs; };
+    extraSpecialArgs = { inherit inputs outputs; };
     users = {
       zyx = import ../home-manager/home.nix;
     };
```

**Comment by Misterio77** [comment]
It's my fault actually for forgetting to include an example for hm as NixOS module, I'll see if I can document this somewhere or add an additional template

**Comment by zyxophobia** [comment]
Ah, I caught it! I feel quite silly for missing that. Thanks!

Also, I got a couple of warnings when checking the new config with `nix flake check`:

- `services.openssh.permitRootLogin` was renamed to `services.openssh.settings.PermitRootLogin`
- `services.openssh.passwordAuthentication` was renamed to `services.openssh.settings.PasswordAuthentication`

Thanks for your assistance with this! I'm happy that you like my silly comments in my config 🙃
