### ISSUE TITLE
Exactly one of users.users..isSystemUser and users.users..isNormalUser must be set.

### ISSUE THREAD

**Issue by lasers** [Misterio77/nix-starter-configs#24]
Hi. Newbie here, I have been using NixOS using non-flake setup for months. I decided to give flake a try and I found several starter configs including yours.

I have this issue with minimal version config, I was able to get `home-manager` working. However, I cannot get `nixos` to work as I kept getting this error. I'm not sure what went wrong so I wonder if it's due to your tinkering around and/or commented out user config.

```
❯ sudo nixos-rebuild switch --flake .#rog 
warning: Git tree '/home/chris/.nixpkgs' is dirty
building the system configuration...
warning: Git tree '/home/chris/.nixpkgs' is dirty
error:
       Failed assertions:
       - Exactly one of users.users..isSystemUser and users.users..isNormalUser must be set.

       - users.users..group is unset. This used to default to
       nogroup, but this is unsafe. For example you can create a group
       for this user with:
       users.users..group = "";
       users.groups. = {};
(use '--show-trace' to show detailed location information)
```
I have `let user = "chris"` and `${user}` in my `/etc/nixos/configuration` for users/groups, but changing it to `chris` still produced this error with invisible user name in the message. I can't tell if I made a mistake.

Unrelated:
* In `nixos-hardware`, `common-ssd` does not exists, but `common-pc-ssd` does. I used this one.
* I also look forward to multiple users/hosts/machines issue too because I have aarch64 (darwin).

**Comment by Misterio77** [comment]
Hello!

You gotta set either `users.users.chris.isNormalUser = true;` in your config! It should work then.
Here's it on the template: https://github.com/Misterio77/nix-starter-configs/blob/main/minimal/nixos/configuration.nix#L71

**Comment by lasers** [comment]
I do have that in my config. No worries. I went back to non-flake for now. One day, I'll get it. Many thanks. :+1:
