### ISSUE TITLE
How to use a modified version of a module?

### ISSUE THREAD

**Issue by voidzero** [Misterio77/nix-starter-configs#28]
Hi! I'd like to make a few changes to this module:

https://github.com/NixOS/nixpkgs/blob/nixos-22.11/nixos/modules/tasks/network-interfaces.nix

But I want to test them for myself before I issue a pull request. How can I do this in the 'standard' flake?

Thanks and have a blessed easter weekend,
Mark

**Comment by Misterio77** [comment]
Hey!

It's actually pretty straightforward.

- Add that module as you would any other:
  - Move it into your `modules/modules/` 
  - List it at `modules/modules/default.nix`
  - Import it in your NixOS config. For example: `{ outputs, ... }: { imports = [ outputs.nixosModules.foo-bar ]`
- You must now disable nixpkgs's version by adding it to a top-level (i.e. next to `options`, `config`, `imports`). `disabledModules` attribute anywhere in your config (I'd recommend you at it at the module itself, [right here](https://github.com/NixOS/nixpkgs/blob/nixos-22.11/nixos/modules/tasks/network-interfaces.nix#L430))

Here's some [docs about replacing modules](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/development/replace-modules.section.md). Hope this helps!

**Comment by voidzero** [comment]
Thanks for the pointers - here and on the Discord channel. :smiley_cat:
