### ISSUE TITLE
Readme "Use home-manager as a NixOS module" section encoutered some issues on my system

### ISSUE THREAD

**Issue by BrycenW** [Misterio77/nix-starter-configs#30]
I'm on a nixos 22.11 system and converted over to nix-start-configs today - thank you, this is great so far!

I ran into some problems with the "Use home-manager as a NixOS module" section:
The  "import ../home-manager" was looking for home-manager/default.nix but the nix file is home.nix. So, I changed that line to:
import ../home-manager/home.nix.

It was failing to compile because the home.nix 'outputs' wasn't defined.
I fixed this by:
Adding 'outputs' to my nixos/configuration.nix parameters
Adding 'outputs' to the extraSpecialArgs for homeManager in configuration.nix

After this it worked great!

Am I doing something wrong here? Or are these actual issues with the README? If so, happy to put up a PR.

**Comment by utkarshgupta137** [comment]
Yeah, both changes are required to get it working.

**Comment by Misterio77** [comment]
Thanks for the heads up!
Yeah, those are issues with the readme. I'd love a PR if you have the time!

It'd be good to also point out in that section  that the `minimal` `flake.nix` does not pass `outputs` through `specialArgs`, only on `standard`.

**Comment by zinou8888** [comment]
> 

thank you so much for this, i was starting to lose my mind because i was unable to set up a basic flake, also big thanks to Misterio77 for this head-start.

**Comment by YanniPapandreou** [comment]
I also encountered this, I will submit a pull-request updating the README, also big thanks to Misterio77 for this template!

**Comment by Misterio77** [comment]
Fixed with #34 and 133826a
