### ISSUE TITLE
Rebuild command in minimal example configuration is missing a word

### ISSUE THREAD

**Issue by gingkapls** [Misterio77/nix-starter-configs#35]
https://github.com/Misterio77/nix-starter-configs/blob/9e4963ae5c1130b18a64db2790248e75a11f94cb/minimal/flake.nix#L22

It should be  `nixos-rebuild switch --flake .#your-hostname`

thanks @phisch for discovering the issue

**Comment by Misterio77** [comment]
Hey!

This is intended, as there's other subcommands besides switch.

**Comment by Misterio77** [comment]
Closing as wontfix, as it's intended!
