### ISSUE TITLE
How to add an overlay?

### ISSUE THREAD

**Issue by Guekka** [Misterio77/nix-starter-configs#4]
First, thanks for this template. I've almost been able to convert my configuration to flakes.
The only thing I'm missing is overlays. I thought just adding them in the overlay folder would be enough, but it looks like it doesn't work?

**Comment by Guekka** [comment]
I'm sorry, but you could please give a small example? I'm not sure if I have to modify the `composeManyExtensions` line
For instance, I'm trying to add openAsar to Discord, which is just a boolean to turn on.

**Comment by tshipenchko** [comment]
For example please show how to use pkgs from unstable with primary stable nixpkgs

**Comment by Guekka** [comment]
So, it appears just pasting my overlay without the `self: super` line inside `modifications` appears to work
However, I'd like to find a way to put it in a separate file

**Comment by Misterio77** [comment]
Sorry for the delay. The idea is that you can add as many overlays as yout want, e.g. import them from a file or declare them directly. Then you just add it to `composeManyExtensions` and you should be good to go. Here's a couple exaples:

Just add them to the existing `overlay/default.nix`:
```nix
{ inputs, ... }:
let
  additions = final: _prev: import ../pkgs { pkgs = final; };
  modifications = final: prev: {
    some-package = prev.some-package.overrideAttrs (oldAttrs: {
      something-something = "foo bar";
    });
  };
in
inputs.nixpkgs.lib.composeManyExtensions [ additions modifications ]
```

Or to a separate file:

`overlays/cool-overlay.nix`:
```nix
final: prev: {
  some-package = prev.some-package.overrideAttrs (oldAttrs: {
    something-something = "foo bar";
  });
}
```

`overlays/default.nix`:
```nix
{ inputs, ... }:
let
  additions = final: _prev: import ../pkgs { pkgs = final; };
  modifications = final: prev: { };
  cool-overlay = import ./cool-overlay.nix;
in
inputs.nixpkgs.lib.composeManyExtensions [ additions modifications cool-overlay ]
```

**Comment by Misterio77** [comment]
As for a dual nixpkgs (stable+unstable) setup:

`flake.nix`
```nix
# ...
inputs = {
  nixpkgs.url = "github:nixos/nixpkgs/nixos-22.05";
  nixpkgs-unstable.url = "github:nixos/nixpkgs/nixos-unstable";
};
# ...
```

`overlays/default.nix`:
```nix
{ inputs, ... }:
let
  additions = final: _prev: import ../pkgs { pkgs = final; };
  modifications = final: prev: { };
  unstable-overrides = final: prev: 
  let pkgs-unstable = inputs.nixpkgs-unstable.legacyPackages.${final.system};
  in {
    hello-unstable = pkgs-unstable.hello;
    neovim-unstable = pkgs-unstable.neovim;
  };
in
inputs.nixpkgs.lib.composeManyExtensions [ additions modifications unstable-overrides ]
```

**Comment by Misterio77** [comment]
Hope these examples help you folks out!

**Comment by Guekka** [comment]
They did! I was able to get Copilot working with clion. Thanks!
