### ISSUE TITLE
ERROR when installing the standard config

### ISSUE THREAD

**Issue by ObvMamut** [Misterio77/nix-starter-configs#42]
Hi, first and foremost I am really new to Nix and NixOS, the last year I spent on Arch and it is really different, I was hoping to install the standard config of this started config so I followed the appropriate steps:
1. I have this in my /etc/nixos/configuration.nix "nix.settings.experimental-features = [ "nix-command" "flakes" ];"
2. I made a new dir: ~/sys/ 
3. I checked if I have the correct nix version with nix --version (i have nix (Nix) 2.4pre-rc1)
4. And i ran this command: nix flake init -t github:misterio77/nix-starter-config#standard
5. Then I edited the configuration.nix to my liking
6. And when I tried to run this command: sudo nixos-rebuild switch --flake .#hostname I get this error: error: flake 'git+file:///home/mamut/sys' does not provide attribute 'packages.x86_64-linux.nixosConfigurations."hostname".config.system.build.nixos-rebuild', 'legacyPackages.x86_64-linux.nixosConfigurations."hostname".config.system.build.nixos-rebuild' or 'nixosConfigurations."hostname".config.system.build.nixos-rebuild'

Please could someone help

**Comment by Misterio77** [comment]
Hi!

`.#hostname` is just an example, you should change it both on the command and [on your flake](https://github.com/Misterio77/nix-starter-configs/blob/main/standard/flake.nix#L62) to your chosen hostname.

**Comment by ObvMamut** [comment]
Ohhhh, damn, I'm stupid. Ily open source Jesus
