### ISSUE TITLE
config.news.json.output not found with home-manager standalone

### ISSUE THREAD

**Issue by daybowbow-dev** [Misterio77/nix-starter-configs#43]
I'm seeing an issue during the first run with home manager news output. When following the standard directions with home-manager (standalone on Pop!_OS) I receive the following error:

`error: flake 'git+file:///home/michaelworthley/code/nix-config' does not provide attribute 'packages.x86_64-linux.homeConfigurations."username@hostname".config.news.json.output', 'legacyPackages.x86_64-linux.homeConfigurations."username@hostname.config.news.json.output' or 'homeConfigurations."username@hostname".config.news.json.output'`

If I run `home-manager switch --flake .#username@hostname` a second time, the error does not show again.

I was able to alleviate the initial run by changing my flake to the following (which I got from `nix run home-manager/[branch] -- init` via the home manager [documentation](https://nix-community.github.io/home-manager/index.html#sec-flakes-standalone):

```
  outputs = { nixpkgs, home-manager, ... }@inputs:
    let
      system = "x86_64-linux";
      pkgs = import nixpkgs
        {
          system = "${system}";
        };
    in
...
 homeConfigurations = {
        # FIXME replace with your username@hostname
        "username@hostname" = home-manager.lib.homeManagerConfiguration {
          inherit pkgs;
          extraSpecialArgs = { inherit inputs; }; # Pass flake inputs to our config
          # > Our main home-manager configuration file <
          modules = [ ./home-manager/home.nix ];
        };
      };
    };
```

I figure the error is not a blocker but as a new Nix user I was confused for a bit. I'm not exactly sure _why_ that fixed it for me, but I figure is has to to with the way nixpkgs is being imported.  Hopefully this issue help anyone else who has run into something similar or if anyone know the "why" behind this I  would love to learn more!

**Comment by qnm** [comment]
Hi @mworthley 

Any ideas what or why your change fixed this issue? I don't use this particular repo but googling this error led me here...!

**Comment by poelzi** [comment]
I see this error now, too

**Comment by winston0410** [comment]
Same error for me

**Comment by mworthley** [comment]
> Hi @mworthley
> 
> Any ideas what or why your change fixed this issue? I don't use this particular repo but googling this error led me here...!

@qnm - No idea, unfortunately. I haven't taken the time to dig into the issue any further as it's been a non-blocker for me.

**Comment by winston0410** [comment]
@mworthley Hey I found the solution

https://github.com/nix-community/home-manager/issues/4533

**Comment by mworthley** [comment]
@winston0410 amazing, great find. Confirming the mismatched versioning on my side. I'm closing out.
