### ISSUE TITLE
[Suggestion] Example / Project Showcase

### ISSUE THREAD

**Issue by FMGordillo** [Misterio77/nix-starter-configs#68]
I think would be awesome to know how people extend their configuration to their own

PS.: If someone has experience with `neovim` and has its configuration there, feel free to share it as well :pleading_face:

**Comment by Cyberczy** [comment]
> I think would be awesome to know how people extend their configuration to their own
> 
> PS.: If someone has experience with `neovim` and has its configuration there, feel free to share it as well 🥺

Perhaps you can try [ayamir/nvimdots](https://github.com/ayamir/nvimdots)

**Comment by juangiordana** [comment]
For Neovim i've been using this flake for months now: https://github.com/mrcjkb/kickstart-nix.nvim

If you use kickstart.nvim you'll find yourself at home right away.

**Comment by juangiordana** [comment]
I started using the minimal nix-starter-config version for a few weeks until I kind of "get it" and then switched to the standard version. Then my configurations grow from that point forward.

I'd recommend not using a repository initially, as editing your .nix files wont take effect unless they're staged or committed.

My setup/flake consists basically from the `nix-stater-config` standard version + `kickstart-nix.nvim` 

```nix
{
  description = "NixOS configurations";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    nixpkgs-stable.url = "github:NixOS/nixpkgs/nixos-23.11";

    hardware.url = "github:NixOS/nixos-hardware";

    home-manager.url = "github:nix-community/home-manager";
    home-manager.inputs.nixpkgs.follows = "nixpkgs";

    # Customo Neovim setup in a flake.
    neovim-flake.url = "path:/home/user/Projects/kickstart-nix.nvim";
    neovim-flake.inputs.nixpkgs.follows = "nixpkgs";
  };
  # ...
}
```

The timeline goes like this:
- Install NixOs
- Move generated config into the minimal/standard nix-starter-config setup.
- Add kickstart-nix.nvim flake.
- Update configs when necessary and then:

```sh
nix flake update
sudo nixos-rebuild --flake .# switch
home-manager --flake .#me@home switch
```

Hope this help :)

**Comment by FMGordillo** [comment]
Thank you both so much!
I will improve slowly but steady with this
I can give my two cents with my current configuration: https://gitlab.com/FMGordillo/nix-config/-/blob/main/home-manager/nixvim.nix?ref_type=heads
