### ISSUE TITLE
`environment.etc` already defined

### ISSUE THREAD

**Issue by crispyricepc** [Misterio77/nix-starter-configs#69]
I need to add a configuration for wireplumber, and the [Nix Wiki suggests this method](https://nixos.wiki/wiki/PipeWire)

I'm not able to do that from `configuration.nix` because environment.etc is already defined. Do you know how I can do that?

**Comment by ksiezak** [comment]
Environment.etc is also needed for persisting files so I also am looking forward for proper solution.

For now I just commented out original definition.

**Comment by Misterio77** [comment]
Hey folks.

`environment.etc` is an attrset. You can simply merge the provided settings with the ones you want to add, for example:

```
  environment.etc =
    (lib.mapAttrs'
    (name: value: {
      name = "nix/path/${name}";
      value.source = value.flake;
    })
    config.nix.registry) // {
      foo = bar;
    };
```

I do plan on cleaning that up, though, as I think the non-nixpkgs registries aren't that useful for 99% of people.

**Comment by Misterio77** [comment]
As of a0fe65b, this settings is simplified a lot and should not generate confusion anymore
