### ISSUE TITLE
File system "/boot" is not a FAT EFI System Partition (ESP) file system

### ISSUE THREAD

**Issue by Nukiloco** [Misterio77/nix-starter-configs#8]
I'm using the VirtualBox nix demo which allows you to modify it. I followed all the fixme's and everything seem to install. However at the end of running ``sudo nixos-rebuild switch --flake .#nixos``, I got this error:
![ORCbIVmHzU](https://user-images.githubusercontent.com/16618467/201115001-0363df6c-63ec-4546-8d58-deaaa61146e4.png)

**Comment by Misterio77** [comment]
Hey, is your ESP mounted correctly?

**Comment by Nukiloco** [comment]
i figured out that I was supposed to generate a hardware-configuration.nix by using nixos-generate-config which I guess I somehow missed that sentence in the README.md. Though I'm not sure if that fixes this issue because I'm getting this issue now:
![XJdJSWaoli](https://user-images.githubusercontent.com/16618467/201126667-bd5d737b-dab3-49f8-ad60-f2fdc0d21f29.png)
however when running the nixos-generate-config config to regenerate the hardware-configuration.nix, it doesn't set the hostPlatforms even though it says it unless if im misunderstanding it?

**Comment by Misterio77** [comment]
Add `nixpkgs.system = "x86_64-linux` to your hardware-configuration.nix, and it should work.

**Comment by Nukiloco** [comment]
It's kind of a weird error because the file tells you to not modify the hardware-configuration.nix but you have to in order to set the hostPlatform?

**Comment by Misterio77** [comment]
> It's kind of a weird error because the file tells you to not modify the hardware-configuration.nix but you have to in order to set the hostPlatform?

You probably used a 22.05 live CD to generate it? Unstable generates it with hostPlatform set

**Comment by Misterio77** [comment]
> Oh I see, the virtualbox demo uses grub while the configuration.nix is wanting to use systemd-boot which is not what I want to use

IIRC the demo uses legacy boot, you probably would prefer EFI on your actual system, though.

**Comment by Nukiloco** [comment]
> > Oh I see, the virtualbox demo uses grub while the configuration.nix is wanting to use systemd-boot which is not what I want to use
> 
> IIRC the demo uses legacy boot, you probably would prefer EFI on your actual system, though.

Ah, i will see if its possible I can switch over to EFI on the virtual machine
Also i guess the reason why it didn't generate because the current configuration on the virtual machine is the stable version which doesn't have it, make sense now

**Comment by Misterio77** [comment]
Let me know if it works :D

**Comment by data-djinn** [comment]
Hey @Nukiloco, I was experiencing this same error message ever since I got in over my head with "erasing my darlings" via btrfs... Anyways, what fixed it for me was removing the line in my `configuration.nix` that specified the location of my EFI: 

`boot.loader.efi.efiSysMountPoint = "/boot/efi";`

Removing that one line fixed the issue for me - NixOS was smart enough to infer the mount point without needing it specified.

let me know if that helps!

btw @Misterio77, thanks for the work you put in to this starter config repo - NixOS has 1 more user thanks to your efforts :)

**Comment by Misterio77** [comment]
AFAICS this has been addressed, so I'll close for now! Feel free to reopen if still affects you.

**Comment by diego898** [comment]
> > > Oh I see, the virtualbox demo uses grub while the configuration.nix is wanting to use systemd-boot which is not what I want to use
> > 
> > 
> > IIRC the demo uses legacy boot, you probably would prefer EFI on your actual system, though.
> 
> Ah, i will see if its possible I can switch over to EFI on the virtual machine Also i guess the reason why it didn't generate because the current configuration on the virtual machine is the stable version which doesn't have it, make sense now

Hello! I have this same issue. Im still new to this though, so Im not quite sure how you fixed it. I am also using virtualbox + nixos and trying to use these configs as a base. 

When I generated a hardware config and overwrote the one in minimimal/nixos/ with it, now It says that I dont have a `fileSystems` key in my file. I think I didnt generate it correctly considering im on vritualbox VM.
