### ISSUE TITLE
Can't use custom package in module?

### ISSUE THREAD

**Issue by thecatwasnot** [Misterio77/nix-starter-configs#9]
Hi,  Thanks so much for providing this to get started with nix.
I've started with the standard template.  I'm trying to copy your shellcolord package and module into my configuration and am having trouble.  Here's the error:
```
cole@pulsar:~/nixfiles/ > home-manager switch --flake .#cole@pulsar                         
error: attribute 'shellcolord' missing

       at /nix/store/4mvzvcj6l01jc51j800hjvhxx02q3afr-source/modules/home-manager/shellcolor.nix:5:13:

            4|   cfg = config.programs.shellcolor;
            5|   package = pkgs.shellcolord;
             |             ^
            6|
```
As far as I can tell, everything looks correct but I'm new and I might be missing something.  Here's my config: https://github.com/thecatwasnot/nixfiles/tree/shellcolor

**Comment by Misterio77** [comment]
Hello!

The newer versions don't implicitly add the overlays to the config, just uncomment this line and it should work: https://github.com/thecatwasnot/nixfiles/blob/shellcolor/home-manager/cole/default.nix#L20

Alternatively, you can use `outputs.packages`:
```nix
package = outputs.packages.${pkgs.system}.shellcolord;

**Comment by thecatwasnot** [comment]
Many thanks!
